### ISSUE TITLE
META: migrate all transitive deps to the latest package_config

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#1177]
This package doesn't directly depend on package_config but 3 of its dependencies do:

- [ ] [analyzer](https://github.com/dart-lang/sdk/issues/40569)
- [x] ~[package_resolver](https://github.com/dart-lang/package_resolver/issues/29)~ deprecate instead
- [x] [coverage](https://github.com/dart-lang/coverage/issues/289) - [PR](https://github.com/dart-lang/coverage/pull/292)

~In order for any package that wants to use package_config to run tests (including package_config itself) we need to migrate all of these.~ It looks like we will be able to make a backwards/forwards compatible release, but should still migrate these packages.

**Comment by jakemac53** [comment]
Also we are considering deprecating package_resolver after looking into migrating it - so that would mean migrating the following to use package_config:

- [shelf_packages_handler](https://github.com/dart-lang/shelf_packages_handler/issues/10)
- test
- test_core
- [source_map_stack_trace](https://github.com/dart-lang/source_map_stack_trace/issues/10)

**Comment by jakemac53** [comment]
Closing as this is effectively done - still waiting on the analyzer but we aren't actually blocked on it.
