### ISSUE TITLE
Support the dev compiler

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#414]
We should eventually support compiling tests using [the dev compiler](/dart-lang/dev_compiler)—it will be faster, less monolithic, and hopefully more cacheable than dart2js.

This is currently blocked on getting `test` and all of its dependencies strong-mode clean.

Note that this issue is only tracking basic support—the only hard requirement is that `test` runs code compiled by the dev compiler. Once this lands, speed or modularity goals will be tracked elsewhere.

**Comment by nex3** [comment]
All the dependencies that get transitively imported by tests are now strong-mode clean, so this is unblocked.

**Comment by nex3** [comment]
This is blocked on dart-lang/sdk#26711. We need better analyzer parsing, but we also need strong-mode-clean dependencies.

**Comment by nex3** [comment]
This is also blocked on dart-lang/dev_compiler#609. We need to be able to compile files over HTTP to support `pub serve`.

**Comment by nex3** [comment]
Also dart-lang/dev_compiler#611.

**Comment by nex3** [comment]
Blocking issues:

- [ ] dart-lang/sdk#26711
- [ ] dart-lang/dev_compiler#609
- [ ] dart-lang/dev_compiler#611
- [ ] dart-lang/dev_compiler#612

**Comment by nex3** [comment]
FYI, I could probably begin work on this with just dart-lang/sdk#27267, dart-lang/sdk#27264, and dart-lang/sdk#27001. I wouldn't be able to release that work, but I could probably get something committed outside of the UI.

**Comment by dgrove** [comment]
@vsmenon what are your thoughts on those issues?

**Comment by vsmenon** [comment]
What's our package:test goal for this Q?
- Support DDC via bazel?
- Support DDC without bazel?
- Support both?

If only the former, are we blocked on anything?  All the hooks we're using internally should just apply.

**Comment by dgrove** [comment]
both, but we could start with bazel.

**Comment by vsmenon** [comment]
Looking @nex3 's list above, DDC relies on the analyzer to resolve URI, load sources.  We might get some of that for free with the refactoring @bwilkerson is looking into here:

https://github.com/dart-lang/sdk/issues/27511

@bwilkerson - does analyzer support general URIs?

The last three issues are DDC though - we could use some help on that if it needs to get done soon.

**Comment by nex3** [comment]
My intention was to start on non-Bazel support. I don't think we have a clear enough Bazel story yet to make it practical to work on it.

**Comment by skybrian** [comment]
I'm curious about why http or data URI's are needed. It seems unlikely that any tests are using those URI's?

**Comment by nex3** [comment]
The `test` package uses them as part of its compilation process.

**Comment by natebosch** [comment]
The supported way to use `DDC` is `build_runner`. We don't have plans to invoke DDC directly from `test`.
