### ISSUE TITLE
Support debugging browser tests

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#45]
This is the meta-issue tracking baseline support for browser debugging. The goal is to make it possible to debug all supported browsers using whatever built-in debug tools (Observatory and/or dev tools) they support.

- [x] Support pause after load in visible browsers: #294
- [x] Expose the Observatory URL for Dartium and content shell: #295 
- [x] Expose the remote debugger URL for PhantomJS: #296 
- [x] Expose the remote debugger URL for content shell: #297
